version: '3.8'
services:
  reporter:    
    deploy:
      mode: replicated
      replicas: 1
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    build: reporter
    environment:
      - TZ=Europe/Moscow
      - MYSQL_SERVER=
      - MYSQL_LOGIN=
      - MYSQL_PASSWORD=
      - MSSQL_SERVER=
      - MSSQL_LOGIN=
      - MSSQL_PASSWORD=
      - TELEGRAM_CHAT=
      - TELEGRAM_BOT_TOKEN=

logger:
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    build: logger
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    network_mode: "host"
    environment:
      - MYSQL_SERVER=
      - MYSQL_LOGIN=root
      - MYSQL_PASSWORD=root
      - PORT=8083
